version: '3'
services:
  load:
    image: ${REPO}/rs-load:${TAG}
    build:
      context: load-gen
    environment:
      HOST: http://web:8080
      ERROR: "0"              # set it to "1" to randomly generate errors
    networks:
      - robot-shop
    depends_on:
      - web
    logging: &logging
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
  website-load:
    image: ${REPO}/rs-website-load:${TAG}
    build:
      context: selenium
    environment:
      HOST: http://web:8080
    networks:
      - robot-shop
    depends_on:
      - web
    logging:
      <<: *logging
